name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_INSTALL_DIR: '.\.dotnet'
    steps:
      - name: Check versions
        run: |
          pwsh -Command '$PSVersionTable'
          dotnet --version
          dotnet --list-sdks
      - name: Setting up dotnet 6 as default SDK
        run: |
          dotnet new globaljson --sdk-version 6.0.0 --roll-forward minor
          dotnet --version
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' 

      - name: Install SonarCloud scanner
        shell: pwsh
        run: dotnet tool install --global dotnet-sonarscanner
      - name: pwd
        shell: pwsh
        run: Get-Location
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: |
          Get-Location
          dotnet-sonarscanner begin /k:"ku3mich_Text.Diff" /o:"ku3mich" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
          dotnet build --configuration Release
          ./run-test.ps1
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
      - name: Pack nugets
        run: ./run-pack.ps1
      - name: Push-nugets
        env:
            NUGET_FEED: https://api.nuget.org/v3/index.json
            NUGET_KEY: ${{ secrets.NUGET_ORG_API_KEY }}
        run: ./run-push.ps1

